// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: vip.proto

package go_micro_srv_vip

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VIP service

type VIPService interface {
	CheckName(ctx context.Context, in *CheckNameRequest, opts ...client.CallOption) (*CheckNameResponse, error)
}

type vIPService struct {
	c    client.Client
	name string
}

func NewVIPService(name string, c client.Client) VIPService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.vip"
	}
	return &vIPService{
		c:    c,
		name: name,
	}
}

func (c *vIPService) CheckName(ctx context.Context, in *CheckNameRequest, opts ...client.CallOption) (*CheckNameResponse, error) {
	req := c.c.NewRequest(c.name, "VIP.CheckName", in)
	out := new(CheckNameResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VIP service

type VIPHandler interface {
	CheckName(context.Context, *CheckNameRequest, *CheckNameResponse) error
}

func RegisterVIPHandler(s server.Server, hdlr VIPHandler, opts ...server.HandlerOption) error {
	type vIP interface {
		CheckName(ctx context.Context, in *CheckNameRequest, out *CheckNameResponse) error
	}
	type VIP struct {
		vIP
	}
	h := &vIPHandler{hdlr}
	return s.Handle(s.NewHandler(&VIP{h}, opts...))
}

type vIPHandler struct {
	VIPHandler
}

func (h *vIPHandler) CheckName(ctx context.Context, in *CheckNameRequest, out *CheckNameResponse) error {
	return h.VIPHandler.CheckName(ctx, in, out)
}
